let modeloJson = [
    {
      id: 1,
      name: 'O Amor não é Óbvio',
      img: 'img/livro1.jpeg',
      price: 31.90,
      sizes: ['', '', ''],
      description: 'Autor(a): Elayne Baeta',
    },
    {
      id: 2,
      name: 'Última Parada',
      img: 'img/livro2.jpeg',
      price: 55.0,
      sizes: ['', '', ''],
      description: 'Autor(a): Casey McQuiston',
    },
    {
      id: 3,
      name: 'Garota do Mar',
      img: 'img/livro3.png',
      price: 50.63,
      sizes: ['', '', ''],
      description: 'Autor(a): Molly Knox Ostertag',
    },
    {
      id: 4,
      name: 'Eu e Esse Meu Coração',
      img: 'img/livro4.png',
      price: 31.44,
      sizes: ['', '', ''],
      description: 'Autor(a): C.C Hunter',
    },
    {
      id: 5,
      name: 'Conectadas',
      img: 'img/livro5.png',
      price: 20.00,
      sizes: ['', '', ''],
      description: 'Autor(a): Clara Alves',
    },
    {
      id: 6,
      name: 'Ela fica com a Garota',
      img: 'img/livro6.png',
      price: 33.16,
      sizes: ['', '', ''],
      description: 'Autor(a): Rachael Lippincott, Alyson Derrick',
    },
  ];